name: Linux Build

on:
  push:
  pull_request:

jobs:
  build-test-run-linux:
    name: Build & Test & Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update repositories
        run: sudo apt-get update -qq

      - name: Install meson build system
        run: |
          sudo apt-get install -y python3 python3-pip valgrind
          python3 -m pip install meson

      - name: Install ninja build system
        run: sudo apt-get install -y ninja-build

      - name: Configure build directory for shared library
        run: meson setup builddir -Dtests=true -Dexamples=true -Ddefault_library=shared

      - name: Compile project
        run: meson compile -C builddir

      - name: Run tests
        run: meson test --wrap='valgrind --leak-check=full --error-exitcode=1' -C builddir

      - name: Start example
        run: builddir/examples/example

      - name: Start single header example
        run: builddir/examples/example-single-header

      - name: Configure build directory for static library
        run: meson configure builddir -Dtests=true -Dexamples=true -Ddefault_library=static

      - name: Compile project
        run: meson compile -C builddir

      - name: Run tests
        run: meson test --wrap='valgrind --leak-check=full --error-exitcode=1' -C builddir

      - name: Start example
        run: builddir/examples/example

      - name: Start single header example
        run: builddir/examples/example-single-header
